version: '3.9'

services:
  scraper:
    build:
      context: ./job_scrape
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./job_scrape:/usr/src/app
    ports:
      - 80:8000
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./job_scrape
    command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./job_scrape:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - scraper
      - redis

  redis:
    image: redis:6-alpine